# Generated by Django 4.2.3 on 2023-07-28 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="second_name",
            new_name="last_name",
        ),
    ]
